project:
  type: website
  output-dir: docs

website:
  title: "SeekandHit Interview Task - David Jankoski"
  search: true
  reader-mode: true
  navbar:
    background: "#2e3f58"
  sidebar:
    style: "floating"
    contents:
      - section: "Task overview"
        contents:
          - index.qmd
          - summary.qmd
      - section: "Analysis"
        contents:
          - country.qmd
          - country_medium.qmd
          - conversion_paths.qmd
      - section: "Appendix"
        contents:
          - colophon.qmd
  page-footer:
    left: "This is quite a fine footer."
    right:
      - icon: github
        href: https://github.com/david-jankoski/seekandhit

format:
  bookup-html:
    embed-fonts: true
    monofont: Fira Code Light
