project:
  type: website
  output-dir: docs

format:
  bookup-html+dark:
    toc: true
    toc-depth: 4
  html:
    theme:
      light:
        - bookup.scss
      dark:
        - bookup_dark.scss

execute:
  freeze: auto

book:
  title: "SeekandHit Interview Task"
  author: "David Jankoski"
  date: today
  downloads: [pdf, epub]
  url: https://david-jankoski.github.io/seekandhit/
  repo-url: https://github.com/david-jankoski/seekandhit
  repo-actions: edit
  search: true
  reader-mode: true
  sidebar:
    style: "docked"
  chapters:
    - index.qmd
    - part: "Content"
      chapters:
        - summary.qmd
        - country.qmd
        - country_medium.qmd
        - conversion_paths.qmd
  appendices:
    - other_ideas.qmd

website:
  search:
    location: navbar
    type: overlay
  sidebar:
    style: "docked"
