---
number-sections: false
echo: false
code-fold: true
monofont: Fira Code Light
execute:
  warning: false
  code-fold: true
---

# Introduction

Hello and welcome to this project in which I tried to explain and present my analysis and thoughts around the interview task that I got from Ivan.

I hope you find it interesting and I am looking forward to presenting it and discussing it with you.

::: {.callout-note icon="false"}
## Task overview

Hi, can you provide me with an in depth analysis of our marketing efforts, based on the data provided in the attachment.

We'd like to focus our activities on markets which we can easily scale while keeping long term profitability.

Overview about our imaginary client:

Client is a global passenger transfer company which focuses on short distance transport. Their customers are mostly people travelling for holidays with family, but around 15% of business also falls in the business travel category.

Due to recent market changes they are looking into optimising their marketing efforts in order to overtake higher market share in the future; currently their main markets are US, UK, Argentina, and South Korea where they are market leaders with 30%+ market share

Their activities are in some markets mostly offline, while in others are just online.
:::

The main goals are:

-   scale markets easily
-   while keeping long term profitability
-   in order to gain higher market share

## Callout

While one of the main points is around keeping *profitability* no data on marketing spend was provided which is essential in order to determine this (for the paid channels like cpc).

Nevertheless, the data provided contained many interesting insights already - and besides that, I think it should not be too hard to also add this aspect to the existing analysis.

For instance, having marketing spend data on (country, channel/medium) level would be helpful to derive important metrics like the channel's return on investment or the cost per acquisition (CPA). The latter coupled with the customer lifetime value (CLV) derives further into the CLV:CPA ratio which speaks about the profitability of the business. One important think to consider is the fact that CPA would depend on the type of attribution model used (which channel did acquire what portion of the customers) and as discussed in the further sections - this could be very different depending on the choice of model.

# Data

-   `medium_country.csv` data aggregated on country / medium level providing some high-level important metrics like \# sesssions, (new) users, transactions, revenue, bounce rate etc. This file is likely the format of the Google Analytics Acquisition Report.
-   `conversion_paths.csv` data containing only the conversion paths that happened on the website and their monetary value. This file is likely the format of the Multi Channel Funnel Report from Google Analytics.

The date ranges in both files judging from the header comments and file names is the full year of 2022.

# Structure of this doc

You can find a [Summary](summary.qmd#Summary) section. This is a condensed format of the main takeaways that tries to just convey the message, links further to charts or tables where the point is displayed in some more detail - and is suitable for a quick and short overview.

The individual sections that look at the different views of the data can be found in:

-   [Country](country.qmd#Country) - view on country level
-   [Country / Medium](country_medium.qmd#Country%20/%20Medium) - analysis of the data provided on country / medium level
-   [Conversion paths](conversion_paths.qmd#Conversion%20paths) - markov model based on the provided conversion paths data

I tried to express there my thoughts and investigations into text and code to reflect my approach to this task.

I hope you find it interesting and I look forward to discussing it with you. All the code for this project can be found [here](https://github.com/david-jankoski/seekandhit).
